Foreground yes
User clamav
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
MaxThreads 4
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 500
MaxScanTime 120000
StreamMaxLength 2147483648
MaxScanSize 2147483648
MaxFileSize 2147483648
MaxRecursion 16
MaxFiles 100000
AlertEncrypted yes
LogTime yes
LogClean no
LogSyslog no
